#!/bin/bash
# postinstall script for forensic toll collection
#
# see: dh_installdeb(1)
set -e

case "$1" in
configure)
  dkms add -m pf_ring -v 4
  dkms build -m pf_ring -v 4
  dkms install -m pf_ring -v 4
;;

abort-upgrade|abort-remove|abort-deconfigure)
;;

*)
echo "postinst called with unknown argument"
  exit 1
;;
esac

#DEBHELPER

exit 0
